/**
 * Admin Support Tickets module
 */

export {
  adminSupportService,
  toAdminSupportDashboardParams,
  mapAdminInboxDateToApiTime,
  toAdminSupportApiSort,
  toAdminSupportApiStatus,
  toAdminSupportApiSourceFilter,
} from "./support.service";
export {
  mapAdminSupportDashboardStats,
  mapAdminSupportQueueStats,
  mapAdminSupportLiveConversations,
  mapAdminSupportStaff,
  mapAdminSupportVenues,
  mapAdminSupportTicketToConversation,
  mapAdminSupportAssignee,
  mapAdminCustomerToContact,
  mapAdminSourceFromTicket,
  flattenAdminSupportMessages,
  getAdminMessagesPayload,
  mapAdminTicketDetailToConversation,
  mapAdminRecentTicketToConversation,
} from "./mappers";
export type { AdminSupportLiveConversationItem } from "./mappers";
export {
  adminSupportKeys,
  useAdminSupportDashboard,
  useAdminSupportTickets,
  useAdminSupportTicketMessages,
  useAdminSupportTicketMessagesInfinite,
  useMarkAdminSupportMessagesRead,
  usePinAdminSupportTicket,
  useAssignAdminSupportTicket,
  useEscalateAdminSupportTicket,
  useCloseAdminSupportTicket,
  useStoreAdminSupportMessage,
  ADMIN_SUPPORT_DASHBOARD_POLL_MS,
  ADMIN_SUPPORT_LIST_POLL_MS,
  ADMIN_SUPPORT_THREAD_POLL_MS,
} from "./query";
export type {
  AdminSupportDashboardResponse,
  AdminSupportDashboardData,
  AdminSupportDashboardParams,
  AdminSupportDashboardTime,
  AdminSupportDashboardQueues,
  AdminSupportDashboardLiveConversation,
  AdminSupportTicket,
  AdminSupportTicketsParams,
  AdminSupportTicketsResponse,
  AdminSupportStaff,
  AdminSupportVenueOption,
  AdminSupportSort,
  AdminSupportTimeFilter,
  AdminSupportQuickFilter,
  AdminSupportTicketPriority,
  AdminSupportTicketSource,
  AdminSupportTicketStatus,
  AdminSupportMessagesParams,
  AdminSupportMessagesResponse,
  AdminSupportMessageGroup,
  AdminSupportMessageItem,
  AdminSupportTicketDetail,
  AdminSupportTicketCustomer,
  AdminSupportTicketAssignee,
  AdminSupportRecentTicket,
  MarkAdminSupportMessagesReadData,
  MarkAdminSupportMessagesReadResponse,
  PinAdminSupportTicketPayload,
  PinAdminSupportTicketResponse,
  AssignAdminSupportTicketPayload,
  AssignAdminSupportTicketResponse,
  EscalateAdminSupportTicketData,
  EscalateAdminSupportTicketResponse,
  CloseAdminSupportTicketPayload,
  CloseAdminSupportTicketResponse,
  AdminSupportClosedReason,
  StoreAdminSupportMessagePayload,
  StoreAdminSupportMessageResponse,
} from "./type";
