import * as z from "zod";

/**
 * Schema for creating new roles (slug is auto-generated by backend)
 */
export const createRoleSchema = z.object({
  label: z
    .string()
    .min(2, {
      message: "Label must be at least 2 characters.",
    })
    .max(50)
    .regex(/^[a-zA-Z0-9\s\-']+$/, {
      message:
        "Role name can only contain letters, numbers, spaces, hyphens, and apostrophes.",
    }),
  permissions: z.array(z.number()).min(1, {
    message: "Select at least one permission.",
  }),
});

/**
 * Schema for updating role permissions (slug is managed by backend)
 */
export const updatePermissionsSchema = z.object({
  label: z
    .string()
    .min(2, {
      message: "Label must be at least 2 characters.",
    })
    .max(50)
    .regex(/^[a-zA-Z0-9\s\-']+$/, {
      message:
        "Role name can only contain letters, numbers, spaces, hyphens, and apostrophes.",
    }),
});

// Export types that can be used in components
export type CreateRoleFormValues = z.infer<typeof createRoleSchema>;
export type UpdatePermissionsFormValues = z.infer<
  typeof updatePermissionsSchema
>;
