import { SystemLogEntry } from "./types";

/** Dummy system logs for admin; replace with API when backend is ready */
export const SYSTEM_LOGS_DUMMY_DATA: SystemLogEntry[] = [
  {
    id: "1",
    timestamp: "2026-02-27T14:22:00Z",
    level: "info",
    action: "admin.login",
    user: "admin@eventwizz.com",
    message: "Admin logged in successfully",
    ip_address: "10.0.0.1",
  },
  {
    id: "2",
    timestamp: "2026-02-27T14:18:00Z",
    level: "info",
    action: "vendor.approved",
    user: "admin@eventwizz.com",
    message: "Vendor 'Riverside Events Centre' approved",
    ip_address: "10.0.0.1",
  },
  {
    id: "3",
    timestamp: "2026-02-27T13:45:00Z",
    level: "warning",
    action: "payment.dispute",
    user: "system",
    message: "Dispute raised for transaction pi_3Supd2BVfJHBZ4zVOZVzzzPm",
    ip_address: undefined,
  },
  {
    id: "4",
    timestamp: "2026-02-27T12:30:00Z",
    level: "info",
    action: "role.updated",
    user: "admin@eventwizz.com",
    message: "Staff role 'Support Agent' permissions updated",
    ip_address: "10.0.0.1",
  },
  {
    id: "5",
    timestamp: "2026-02-27T11:15:00Z",
    level: "error",
    action: "email.send_failed",
    user: "system",
    message: "Failed to send bulk notification to 3 vendors",
    ip_address: undefined,
  },
  {
    id: "6",
    timestamp: "2026-02-27T10:00:00Z",
    level: "info",
    action: "venue.updated",
    user: "admin@eventwizz.com",
    message: "Venue 'Victoria & Albert Hall' details updated by admin",
    ip_address: "10.0.0.1",
  },
  {
    id: "7",
    timestamp: "2026-02-26T17:20:00Z",
    level: "info",
    action: "user.impersonate",
    user: "admin@eventwizz.com",
    message: "Admin logged in as vendor sahil@so-creative.co.uk",
    ip_address: "10.0.0.1",
  },
  {
    id: "8",
    timestamp: "2026-02-26T16:00:00Z",
    level: "info",
    action: "commission.payout",
    user: "system",
    message: "Scheduled commission payout completed for 12 vendors",
    ip_address: undefined,
  },
  {
    id: "9",
    timestamp: "2026-02-26T14:30:00Z",
    level: "warning",
    action: "login.failed",
    user: "unknown",
    message: "5 failed login attempts from IP 203.0.113.42",
    ip_address: "203.0.113.42",
  },
  {
    id: "10",
    timestamp: "2026-02-26T11:00:00Z",
    level: "info",
    action: "site_essential.updated",
    user: "admin@eventwizz.com",
    message: "Global site essentials (footer links) updated",
    ip_address: "10.0.0.1",
  },
];
