import { MenuItemProps } from "./types";
import { createVendorUrl } from "./utils";

// Vendor Menus
export const vendorMenus: MenuItemProps[] = [
  {
    id: 1,
    title: "Dashboard",
    icon: "dashboard",
    href: createVendorUrl("/vendor/dashboard"),
    url: createVendorUrl("/vendor/dashboard"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 2,
    title: "Events",
    icon: "events",
    href: createVendorUrl("/vendor/events"),
    url: createVendorUrl("/vendor/events"),
    type: "title",
    permissions: "",
  },
  {
    id: 3,
    title: "Customers",
    icon: "customers",
    href: createVendorUrl("/vendor/customers"),
    url: createVendorUrl("/vendor/customers"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 4,
    title: "Bookings",
    icon: "bookings",
    href: createVendorUrl("/vendor/booking-history"),
    url: createVendorUrl("/vendor/booking-history"),
    type: "title",
    permissions: "",
  },
  {
    id: 5,
    title: "Email Templates",
    icon: "emailTemplates",
    href: createVendorUrl("/vendor/email-templates"),
    url: createVendorUrl("/vendor/email-templates"),
    type: "title",
    permissions: "read-email-template",
    menu: [],
  },
  {
    id: 6,
    title: "Menu Choice",
    icon: "menuChoice",
    href: createVendorUrl("/vendor/menu-choices"),
    url: createVendorUrl("/vendor/menu-choices"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 7,
    title: "Transactions",
    icon: "payments",
    href: createVendorUrl("/vendor/transactions"),
    url: createVendorUrl("/vendor/transactions"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 8,
    title: "Sites Essentials",
    icon: "sitesEssentials",
    href: createVendorUrl("/vendor/sites-essentials"),
    url: createVendorUrl("/vendor/sites-essentials"),
    type: "title",
    permissions: "read-site-essentials",
    menu: [],
  },
  {
    id: 9,
    title: "Event Locations",
    icon: "eventLocations",
    href: createVendorUrl("/vendor/venue-locations"),
    url: createVendorUrl("/vendor/venue-locations"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 10,
    title: "Marketing",
    icon: "marketing",
    href: createVendorUrl("/vendor/marketing"),
    url: createVendorUrl("/vendor/marketing"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 11,
    title: "Newsletter",
    icon: "newsletter",
    href: createVendorUrl("/vendor/newsletter"),
    url: createVendorUrl("/vendor/newsletter"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 12,
    title: "Email Logs",
    icon: "emailLogs",
    href: createVendorUrl("/vendor/email-logs"),
    url: createVendorUrl("/vendor/email-logs"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 13,
    title: "Manage Roles",
    icon: "manageRoles",
    href: createVendorUrl("/vendor/manage-roles"),
    url: createVendorUrl("/vendor/manage-roles"),
    type: "title",
    permissions: "roles.read",
    menu: [],
  },
  {
    id: 14,
    title: "Staff Management",
    icon: "staffManagement",
    href: createVendorUrl("/vendor/staff-management"),
    url: createVendorUrl("/vendor/staff-management"),
    type: "title",
    permissions: "staff.read",
    menu: [],
  },
  {
    id: 15,
    title: "Seo Tools",
    icon: "seoTools",
    href: createVendorUrl("/vendor/seo-tools"),
    url: createVendorUrl("/vendor/seo-tools"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 16,
    title: "Notifications",
    icon: "notifications",
    href: createVendorUrl("/vendor/notifications"),
    url: createVendorUrl("/vendor/notifications"),
    type: "title",
    permissions: "",
    menu: [],
  },
  {
    id: 17,
    title: "Support",
    icon: "support",
    href: createVendorUrl("/vendor/support"),
    url: createVendorUrl("/vendor/support"),
    type: "title",
    permissions: "read-ticket",
    menu: [],
  },
  {
    id: 18,
    title: "Dispute Resolution",
    icon: "disputeResolution",
    href: createVendorUrl("/vendor/dispute-resolution"),
    url: createVendorUrl("/vendor/dispute-resolution"),
    type: "title",
    permissions: "",
    menu: [],
  },
];
